version: "3"

services:
  backend: # 10101
    build: ./backend
    restart: always
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USERNAME=$DB_USERNAME
    depends_on:
      - db
      - redis

  nginx: # 8080 -> 80
    image: nginx:alpine
    ports:
     - "8080:80"
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
     - backend

  db: # 3306
    image: mysql
    restart: always
    volumes:
      - ./db/db_data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DB_USERNAME=$DB_USERNAME
      - MYSQL_DB_PASSWORD=$DB_PASSWORD

  # redis redis-server --save 60 1 --loglevel warning
  redis: # 6379 -> https://dev.to/vjnvisakh/redis-container-and-persisting-939 
    image: redis
    command: sh -c "redis-server --save 60 1 --loglevel warning"
    restart: always
    volumes:
      - ./redis/data:/data
      